-- 0004 — the portals' own data, in schema `portal`.
--
-- GENERATED by scripts/merge/gen-portal-schema.py from the production `gbg` structure
-- (pg_dump --schema-only, 2026-09-17). Edit the generator, not this file.
--
-- Kept from `gbg`: 16 type, 8 function, 24 table, 2 sequence, 2 sequence owned by, 2 default, 35 constraint, 36 fk constraint, 27 index, 8 trigger.
-- Left out: the Zuper mirror (assets, customers, zuper_records, zuper_sync_runs, zuper_webhook_events) — `jms.*` replaces it.
-- See docs/DATABASE-MERGE.md.
BEGIN;

CREATE SCHEMA IF NOT EXISTS portal;

-- TYPE: customer_decision
CREATE TYPE portal.customer_decision AS ENUM (
    'release_green',
    'release_advisory',
    'release_override_red',
    'repair_quote_requested'
);

-- TYPE: decision_actor_role
CREATE TYPE portal.decision_actor_role AS ENUM (
    'client',
    'staff'
);

-- TYPE: decision_channel
CREATE TYPE portal.decision_channel AS ENUM (
    'portal',
    'phone',
    'whatsapp',
    'email'
);

-- TYPE: final_colour
CREATE TYPE portal.final_colour AS ENUM (
    'red',
    'amber',
    'green'
);

-- TYPE: job_step_key
CREATE TYPE portal.job_step_key AS ENUM (
    'inspection_review',
    'inspection_results',
    'vehicle_handover',
    'job_completed',
    'report_sent',
    'under_repair_completed'
);

-- TYPE: job_step_push_state
CREATE TYPE portal.job_step_push_state AS ENUM (
    'not_required',
    'queued',
    'pushed',
    'failed'
);

-- TYPE: job_step_state
CREATE TYPE portal.job_step_state AS ENUM (
    'pending',
    'in_progress',
    'submitted'
);

-- TYPE: pipeline_state
CREATE TYPE portal.pipeline_state AS ENUM (
    'pending_review',
    'in_review',
    'rectification',
    'final_review',
    'completed',
    'issued',
    'ingest_failed'
);

-- TYPE: quotation_status
CREATE TYPE portal.quotation_status AS ENUM (
    'sent',
    'agreed',
    'declined'
);

-- TYPE: rectification_status
CREATE TYPE portal.rectification_status AS ENUM (
    'open',
    'in_progress',
    'closed',
    'cancelled'
);

-- TYPE: report_version_status
CREATE TYPE portal.report_version_status AS ENUM (
    'draft',
    'locked'
);

-- TYPE: resolution_state
CREATE TYPE portal.resolution_state AS ENUM (
    'open',
    'resolved',
    'returned',
    'superseded'
);

-- TYPE: review_item_kind
CREATE TYPE portal.review_item_kind AS ENUM (
    'review',
    'hold',
    'applicability',
    'direct_colour',
    'unmatched'
);

-- TYPE: reviewer_decision
CREATE TYPE portal.reviewer_decision AS ENUM (
    'assign_red',
    'assign_amber',
    'no_adverse_finding',
    'hold_cleared',
    'hold_carried',
    'rectification_required',
    'na_confirmed',
    'applicable_reclassified',
    'acknowledged'
);

-- TYPE: snapshot_source
CREATE TYPE portal.snapshot_source AS ENUM (
    'api_poll',
    'manual_fetch',
    'file_upload'
);

-- TYPE: staff_role
CREATE TYPE portal.staff_role AS ENUM (
    'reviewer',
    'approver',
    'admin'
);

-- FUNCTION: gbg_applicability_protect()
CREATE FUNCTION portal.gbg_applicability_protect() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO portal, pg_temp
    AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'applicability_determinations rows cannot be deleted (determination history is permanent)';
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.scope IS DISTINCT FROM OLD.scope
     OR NEW.asset_identity IS DISTINCT FROM OLD.asset_identity
     OR NEW.fleet_class IS DISTINCT FROM OLD.fleet_class
     OR NEW.decision_identity IS DISTINCT FROM OLD.decision_identity
     OR NEW.outcome IS DISTINCT FROM OLD.outcome
     OR NEW.basis IS DISTINCT FROM OLD.basis
     OR NEW.authority_reference IS DISTINCT FROM OLD.authority_reference
     OR NEW.ma_gate IS DISTINCT FROM OLD.ma_gate
     OR NEW.ma_revision IS DISTINCT FROM OLD.ma_revision
     OR NEW.confirmed_by IS DISTINCT FROM OLD.confirmed_by
     OR NEW.confirmed_by_name IS DISTINCT FROM OLD.confirmed_by_name
     OR NEW.confirmed_at IS DISTINCT FROM OLD.confirmed_at
  THEN
    RAISE EXCEPTION 'applicability_determinations rows are immutable: only supersession and invalidation may be recorded';
  END IF;

  -- Closing out is one-way.
  IF OLD.superseded_at IS NOT NULL AND NEW.superseded_at IS DISTINCT FROM OLD.superseded_at THEN
    RAISE EXCEPTION 'applicability_determinations: supersession cannot be changed once recorded';
  END IF;
  IF OLD.invalidated_at IS NOT NULL AND NEW.invalidated_at IS DISTINCT FROM OLD.invalidated_at THEN
    RAISE EXCEPTION 'applicability_determinations: invalidation cannot be changed once recorded';
  END IF;

  RETURN NEW;
END;
$$;

-- FUNCTION: gbg_applicability_reviewer_only()
CREATE FUNCTION portal.gbg_applicability_reviewer_only() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO portal, pg_temp
    AS $$
DECLARE
  is_reviewer boolean;
BEGIN
  SELECT applicability_reviewer INTO is_reviewer FROM staff_users WHERE id = NEW.confirmed_by;
  IF is_reviewer IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'applicability_determinations: % is not the Applicability Reviewer', NEW.confirmed_by_name;
  END IF;
  RETURN NEW;
END;
$$;

-- FUNCTION: gbg_audit_log_append_only()
CREATE FUNCTION portal.gbg_audit_log_append_only() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO portal, pg_temp
    AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only: % is not allowed', TG_OP;
END;
$$;

-- FUNCTION: gbg_engine_snapshots_immutable()
CREATE FUNCTION portal.gbg_engine_snapshots_immutable() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO portal, pg_temp
    AS $$
BEGIN
  RAISE EXCEPTION 'engine_snapshots rows are immutable: % is not allowed', TG_OP;
END;
$$;

-- FUNCTION: gbg_job_status_step_revisions_append_only()
CREATE FUNCTION portal.gbg_job_status_step_revisions_append_only() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO portal, pg_temp
    AS $$
BEGIN
  RAISE EXCEPTION 'job_status_step_revisions is append-only: % is not allowed', TG_OP;
END;
$$;

-- FUNCTION: gbg_job_status_steps_touch()
CREATE FUNCTION portal.gbg_job_status_steps_touch() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO portal, pg_temp
    AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- FUNCTION: gbg_job_step_attachments_token_frozen()
CREATE FUNCTION portal.gbg_job_step_attachments_token_frozen() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO portal, pg_temp
    AS $$
BEGIN
  IF NEW.token IS DISTINCT FROM OLD.token THEN
    RAISE EXCEPTION 'job_step_attachments.token cannot be changed; delete and re-upload instead';
  END IF;
  IF NEW.bytes IS DISTINCT FROM OLD.bytes THEN
    RAISE EXCEPTION 'job_step_attachments.bytes cannot be changed; delete and re-upload instead';
  END IF;
  IF NEW.object_key IS DISTINCT FROM OLD.object_key THEN
    RAISE EXCEPTION 'job_step_attachments.object_key cannot be changed; delete and re-upload instead';
  END IF;
  RETURN NEW;
END;
$$;

-- FUNCTION: gbg_report_versions_protect()
CREATE FUNCTION portal.gbg_report_versions_protect() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO portal, pg_temp
    AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'report_versions rows cannot be deleted (version history is permanent)';
  END IF;
  IF OLD.status = 'draft' THEN
    RETURN NEW;
  END IF;
  -- OLD.status = 'locked': every column except the PDF artifact columns
  -- (pdf_object_key, pdf_bytes, pdf_generated_at) must be unchanged.
  IF ROW(NEW.id, NEW.job_id, NEW.version, NEW.snapshot_id, NEW.staff_model,
         NEW.client_model, NEW.staff_overlay, NEW.html_staff, NEW.html_client,
         NEW.status, NEW.created_at, NEW.locked_at, NEW.locked_by)
     IS DISTINCT FROM
     ROW(OLD.id, OLD.job_id, OLD.version, OLD.snapshot_id, OLD.staff_model,
         OLD.client_model, OLD.staff_overlay, OLD.html_staff, OLD.html_client,
         OLD.status, OLD.created_at, OLD.locked_at, OLD.locked_by) THEN
    RAISE EXCEPTION 'report_version % is locked: only the PDF columns (pdf_object_key, pdf_bytes, pdf_generated_at) may be backfilled', OLD.id;
  END IF;
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

-- TABLE: applicability_determinations
CREATE TABLE portal.applicability_determinations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    scope text NOT NULL,
    asset_identity text,
    fleet_class text,
    decision_identity text NOT NULL,
    outcome text NOT NULL,
    basis text NOT NULL,
    authority_reference text NOT NULL,
    ma_gate text NOT NULL,
    ma_revision text,
    confirmed_by uuid NOT NULL,
    confirmed_by_name text NOT NULL,
    confirmed_at timestamp with time zone DEFAULT now() NOT NULL,
    superseded_at timestamp with time zone,
    superseded_by uuid,
    invalidated_at timestamp with time zone,
    invalidated_reason text,
    CONSTRAINT applicability_basis_ck CHECK ((basis = ANY (ARRAY['GOVERNED'::text, 'INTERIM'::text]))),
    CONSTRAINT applicability_identity_ck CHECK ((((scope = 'asset'::text) AND (asset_identity IS NOT NULL) AND (fleet_class IS NULL)) OR ((scope = 'fleet'::text) AND (fleet_class IS NOT NULL) AND (asset_identity IS NULL)))),
    CONSTRAINT applicability_interim_revision_ck CHECK (((basis <> 'INTERIM'::text) OR (ma_revision IS NOT NULL))),
    CONSTRAINT applicability_invalidated_ck CHECK (((invalidated_at IS NULL) = (invalidated_reason IS NULL))),
    CONSTRAINT applicability_outcome_ck CHECK ((outcome = ANY (ARRAY['CONFIRMED NOT APPLICABLE'::text, 'CONFIRMED APPLICABLE'::text, 'UNDETERMINABLE'::text]))),
    CONSTRAINT applicability_scope_ck CHECK ((scope = ANY (ARRAY['asset'::text, 'fleet'::text])))
);

-- TABLE: audit_log
CREATE TABLE portal.audit_log (
    id bigint NOT NULL,
    action text NOT NULL,
    job_id uuid,
    actor_id uuid,
    actor_role text,
    subject_type text,
    subject_id text,
    detail jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    real_actor_id uuid,
    real_actor_email text
);

-- SEQUENCE: audit_log_id_seq
CREATE SEQUENCE portal.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- SEQUENCE OWNED BY: audit_log_id_seq
ALTER SEQUENCE portal.audit_log_id_seq OWNED BY portal.audit_log.id;

-- TABLE: client_users
CREATE TABLE portal.client_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    name text,
    customer_id uuid,
    password_hash text,
    password_updated_at bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    super_user boolean DEFAULT false NOT NULL,
    last_sign_in_at timestamp with time zone
);

-- TABLE: customer_decisions
CREATE TABLE portal.customer_decisions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    issuance_id uuid NOT NULL,
    job_id uuid NOT NULL,
    outcome_context text NOT NULL,
    decision portal.customer_decision NOT NULL,
    channel portal.decision_channel NOT NULL,
    decided_by_role portal.decision_actor_role NOT NULL,
    decided_by_actor text,
    on_behalf_of_customer boolean DEFAULT false NOT NULL,
    note text,
    decided_at timestamp with time zone DEFAULT now() NOT NULL,
    superseded_at timestamp with time zone
);

-- TABLE: engine_snapshots
CREATE TABLE portal.engine_snapshots (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    seq integer NOT NULL,
    payload_hash text NOT NULL,
    raw_payload jsonb NOT NULL,
    classified jsonb NOT NULL,
    engine_version text,
    master_list_version text,
    checklist_def_version text,
    source portal.snapshot_source NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- TABLE: governed_drt_rules
CREATE TABLE portal.governed_drt_rules (
    rule_id text NOT NULL,
    scope_zrc text,
    rule_type text,
    inputs text,
    logic_and_outputs text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- TABLE: governed_rows
CREATE TABLE portal.governed_rows (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    zrc text NOT NULL,
    section text NOT NULL,
    ord integer DEFAULT 0 NOT NULL,
    item text,
    label text NOT NULL,
    option text NOT NULL,
    cls text,
    treatment text NOT NULL,
    drt_rule_id text,
    reviewer_requirement text,
    reviewer_required boolean DEFAULT false NOT NULL,
    applicability_confirmation text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- TABLE: governed_seed_state
CREATE TABLE portal.governed_seed_state (
    seed_key text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);

-- TABLE: issuances
CREATE TABLE portal.issuances (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    report_version_id uuid NOT NULL,
    job_id uuid NOT NULL,
    customer_id uuid NOT NULL,
    issued_to_email text NOT NULL,
    issued_by uuid,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    notified_at timestamp with time zone,
    revoked_at timestamp with time zone,
    revoked_by uuid,
    revoke_reason text
);

-- TABLE: job_status_step_revisions
CREATE TABLE portal.job_status_step_revisions (
    id bigint NOT NULL,
    step_id uuid NOT NULL,
    revision integer NOT NULL,
    answers jsonb NOT NULL,
    checklist_key text,
    checklist_digest text,
    submitted_by uuid,
    submitted_at timestamp with time zone DEFAULT now() NOT NULL,
    note text
);

-- SEQUENCE: job_status_step_revisions_id_seq
CREATE SEQUENCE portal.job_status_step_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- SEQUENCE OWNED BY: job_status_step_revisions_id_seq
ALTER SEQUENCE portal.job_status_step_revisions_id_seq OWNED BY portal.job_status_step_revisions.id;

-- TABLE: job_status_steps
CREATE TABLE portal.job_status_steps (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    step_key portal.job_step_key NOT NULL,
    state portal.job_step_state DEFAULT 'pending'::portal.job_step_state NOT NULL,
    checklist_key text,
    checklist_digest text,
    draft jsonb DEFAULT '{}'::jsonb NOT NULL,
    draft_revision integer DEFAULT 0 NOT NULL,
    last_saved_by uuid,
    last_saved_at timestamp with time zone,
    submitted jsonb,
    submitted_by uuid,
    submitted_at timestamp with time zone,
    push_state portal.job_step_push_state DEFAULT 'not_required'::portal.job_step_push_state NOT NULL,
    pushed_at timestamp with time zone,
    push_attempts integer DEFAULT 0 NOT NULL,
    push_error text,
    zuper_status_uid text,
    zuper_status_name text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT job_status_steps_push_accounted CHECK ((((push_state <> 'pushed'::portal.job_step_push_state) OR (pushed_at IS NOT NULL)) AND ((push_state <> 'failed'::portal.job_step_push_state) OR (push_error IS NOT NULL)))),
    CONSTRAINT job_status_steps_submitted_attributed CHECK (((state <> 'submitted'::portal.job_step_state) OR ((submitted IS NOT NULL) AND (submitted_by IS NOT NULL) AND (submitted_at IS NOT NULL))))
);

-- TABLE: job_step_attachments
CREATE TABLE portal.job_step_attachments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    step_id uuid NOT NULL,
    field_key text NOT NULL,
    token text NOT NULL,
    file_name text NOT NULL,
    content_type text NOT NULL,
    byte_size integer NOT NULL,
    bytes bytea,
    uploaded_by uuid,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL,
    object_key text,
    CONSTRAINT job_step_attachments_not_empty CHECK ((byte_size > 0)),
    CONSTRAINT job_step_attachments_stored_once CHECK (((bytes IS NOT NULL) <> (object_key IS NOT NULL)))
);

-- TABLE: jobs
CREATE TABLE portal.jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    zuper_job_uid text NOT NULL,
    work_order_number text,
    customer_id uuid,
    asset_id uuid,
    zuper_status text,
    pipeline_state portal.pipeline_state DEFAULT 'pending_review'::portal.pipeline_state NOT NULL,
    assigned_reviewer_id uuid,
    current_snapshot_id uuid,
    current_report_version_id uuid,
    drift_flag boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    scheduled_start timestamp with time zone
);

-- TABLE: legacy_reports
CREATE TABLE portal.legacy_reports (
    id text NOT NULL,
    record jsonb NOT NULL,
    file bytea,
    source_file_name text,
    customer_email text NOT NULL,
    uploaded_at timestamp with time zone NOT NULL
);

-- TABLE: notifications
CREATE TABLE portal.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kind text NOT NULL,
    recipient_email text NOT NULL,
    subject text,
    payload jsonb,
    status text DEFAULT 'pending'::text NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sent_at timestamp with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    last_attempt_at timestamp with time zone
);

-- TABLE: portal_enrollment_pins
CREATE TABLE portal.portal_enrollment_pins (
    email text NOT NULL,
    customer_uid text NOT NULL,
    customer_name text NOT NULL,
    pin_hash text NOT NULL,
    expires_at bigint NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    sent_at bigint NOT NULL,
    used_at bigint
);

-- TABLE: portal_password_reset_tokens
CREATE TABLE portal.portal_password_reset_tokens (
    token_hash text NOT NULL,
    email text NOT NULL,
    expires_at bigint NOT NULL,
    used_at bigint,
    created_at bigint NOT NULL
);

-- TABLE: portal_password_setup_tokens
CREATE TABLE portal.portal_password_setup_tokens (
    token_hash text NOT NULL,
    email text NOT NULL,
    customer_uid text NOT NULL,
    customer_name text NOT NULL,
    expires_at bigint NOT NULL,
    used_at bigint,
    created_at bigint NOT NULL
);

-- TABLE: quotations
CREATE TABLE portal.quotations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    issuance_id uuid NOT NULL,
    token text NOT NULL,
    file_name text NOT NULL,
    content_type text NOT NULL,
    byte_size integer NOT NULL,
    bytes bytea NOT NULL,
    status portal.quotation_status DEFAULT 'sent'::portal.quotation_status NOT NULL,
    sent_channels jsonb DEFAULT '[]'::jsonb NOT NULL,
    note text,
    created_by uuid,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    decided_at timestamp with time zone,
    superseded_at timestamp with time zone
);

-- TABLE: rectifications
CREATE TABLE portal.rectifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    review_item_id uuid NOT NULL,
    job_id uuid NOT NULL,
    description text NOT NULL,
    action_taken text,
    performed_by text,
    reinspection_snapshot_id uuid,
    status portal.rectification_status DEFAULT 'open'::portal.rectification_status NOT NULL,
    raised_by uuid,
    raised_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_by uuid,
    closed_at timestamp with time zone
);

-- TABLE: report_versions
CREATE TABLE portal.report_versions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    version integer NOT NULL,
    snapshot_id uuid NOT NULL,
    staff_model jsonb,
    client_model jsonb,
    staff_overlay jsonb,
    html_staff text,
    html_client text,
    pdf_object_key text,
    status portal.report_version_status DEFAULT 'draft'::portal.report_version_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    locked_at timestamp with time zone,
    locked_by uuid,
    pdf_bytes bytea,
    pdf_generated_at timestamp with time zone
);

-- TABLE: review_items
CREATE TABLE portal.review_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    snapshot_id uuid NOT NULL,
    kind portal.review_item_kind NOT NULL,
    zrc text,
    question text NOT NULL,
    answer text NOT NULL,
    treatment text,
    documentary_class text,
    requires_evidence boolean DEFAULT false NOT NULL,
    resolution_state portal.resolution_state DEFAULT 'open'::portal.resolution_state NOT NULL,
    reviewer_decision portal.reviewer_decision,
    final_colour portal.final_colour,
    reviewer_id uuid,
    decided_at timestamp with time zone,
    decision_reason text,
    evidence jsonb,
    applicability_ref text,
    superseded_by_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    requirement_source text
);

-- TABLE: staff_password_reset_tokens
CREATE TABLE portal.staff_password_reset_tokens (
    token_hash text NOT NULL,
    staff_id uuid NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- TABLE: staff_users
CREATE TABLE portal.staff_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    name text NOT NULL,
    role portal.staff_role NOT NULL,
    password_hash text NOT NULL,
    password_updated_at bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    super_user boolean DEFAULT false NOT NULL,
    applicability_reviewer boolean DEFAULT false NOT NULL,
    signature_object_key text,
    signature_content_type text,
    signature_updated_at timestamp with time zone
);

-- DEFAULT: audit_log id
ALTER TABLE ONLY portal.audit_log ALTER COLUMN id SET DEFAULT nextval('portal.audit_log_id_seq'::regclass);

-- DEFAULT: job_status_step_revisions id
ALTER TABLE ONLY portal.job_status_step_revisions ALTER COLUMN id SET DEFAULT nextval('portal.job_status_step_revisions_id_seq'::regclass);

-- CONSTRAINT: applicability_determinations applicability_determinations_pkey
ALTER TABLE ONLY portal.applicability_determinations
    ADD CONSTRAINT applicability_determinations_pkey PRIMARY KEY (id);

-- CONSTRAINT: audit_log audit_log_pkey
ALTER TABLE ONLY portal.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

-- CONSTRAINT: client_users client_users_email_unique
ALTER TABLE ONLY portal.client_users
    ADD CONSTRAINT client_users_email_unique UNIQUE (email);

-- CONSTRAINT: client_users client_users_pkey
ALTER TABLE ONLY portal.client_users
    ADD CONSTRAINT client_users_pkey PRIMARY KEY (id);

-- CONSTRAINT: customer_decisions customer_decisions_pkey
ALTER TABLE ONLY portal.customer_decisions
    ADD CONSTRAINT customer_decisions_pkey PRIMARY KEY (id);

-- CONSTRAINT: engine_snapshots engine_snapshots_job_seq_uq
ALTER TABLE ONLY portal.engine_snapshots
    ADD CONSTRAINT engine_snapshots_job_seq_uq UNIQUE (job_id, seq);

-- CONSTRAINT: engine_snapshots engine_snapshots_pkey
ALTER TABLE ONLY portal.engine_snapshots
    ADD CONSTRAINT engine_snapshots_pkey PRIMARY KEY (id);

-- CONSTRAINT: governed_drt_rules governed_drt_rules_pkey
ALTER TABLE ONLY portal.governed_drt_rules
    ADD CONSTRAINT governed_drt_rules_pkey PRIMARY KEY (rule_id);

-- CONSTRAINT: governed_rows governed_rows_label_option_uq
ALTER TABLE ONLY portal.governed_rows
    ADD CONSTRAINT governed_rows_label_option_uq UNIQUE (label, option);

-- CONSTRAINT: governed_rows governed_rows_pkey
ALTER TABLE ONLY portal.governed_rows
    ADD CONSTRAINT governed_rows_pkey PRIMARY KEY (id);

-- CONSTRAINT: governed_seed_state governed_seed_state_pkey
ALTER TABLE ONLY portal.governed_seed_state
    ADD CONSTRAINT governed_seed_state_pkey PRIMARY KEY (seed_key);

-- CONSTRAINT: issuances issuances_pkey
ALTER TABLE ONLY portal.issuances
    ADD CONSTRAINT issuances_pkey PRIMARY KEY (id);

-- CONSTRAINT: job_status_step_revisions job_status_step_revisions_pkey
ALTER TABLE ONLY portal.job_status_step_revisions
    ADD CONSTRAINT job_status_step_revisions_pkey PRIMARY KEY (id);

-- CONSTRAINT: job_status_step_revisions job_status_step_revisions_step_revision
ALTER TABLE ONLY portal.job_status_step_revisions
    ADD CONSTRAINT job_status_step_revisions_step_revision UNIQUE (step_id, revision);

-- CONSTRAINT: job_status_steps job_status_steps_job_step_key
ALTER TABLE ONLY portal.job_status_steps
    ADD CONSTRAINT job_status_steps_job_step_key UNIQUE (job_id, step_key);

-- CONSTRAINT: job_status_steps job_status_steps_pkey
ALTER TABLE ONLY portal.job_status_steps
    ADD CONSTRAINT job_status_steps_pkey PRIMARY KEY (id);

-- CONSTRAINT: job_step_attachments job_step_attachments_field_uq
ALTER TABLE ONLY portal.job_step_attachments
    ADD CONSTRAINT job_step_attachments_field_uq UNIQUE (step_id, field_key);

-- CONSTRAINT: job_step_attachments job_step_attachments_pkey
ALTER TABLE ONLY portal.job_step_attachments
    ADD CONSTRAINT job_step_attachments_pkey PRIMARY KEY (id);

-- CONSTRAINT: job_step_attachments job_step_attachments_token_uq
ALTER TABLE ONLY portal.job_step_attachments
    ADD CONSTRAINT job_step_attachments_token_uq UNIQUE (token);

-- CONSTRAINT: jobs jobs_pkey
ALTER TABLE ONLY portal.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);

-- CONSTRAINT: jobs jobs_zuper_job_uid_unique
ALTER TABLE ONLY portal.jobs
    ADD CONSTRAINT jobs_zuper_job_uid_unique UNIQUE (zuper_job_uid);

-- CONSTRAINT: legacy_reports legacy_reports_pkey
ALTER TABLE ONLY portal.legacy_reports
    ADD CONSTRAINT legacy_reports_pkey PRIMARY KEY (id);

-- CONSTRAINT: notifications notifications_pkey
ALTER TABLE ONLY portal.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

-- CONSTRAINT: portal_enrollment_pins portal_enrollment_pins_pkey
ALTER TABLE ONLY portal.portal_enrollment_pins
    ADD CONSTRAINT portal_enrollment_pins_pkey PRIMARY KEY (email);

-- CONSTRAINT: portal_password_reset_tokens portal_password_reset_tokens_pkey
ALTER TABLE ONLY portal.portal_password_reset_tokens
    ADD CONSTRAINT portal_password_reset_tokens_pkey PRIMARY KEY (token_hash);

-- CONSTRAINT: portal_password_setup_tokens portal_password_setup_tokens_pkey
ALTER TABLE ONLY portal.portal_password_setup_tokens
    ADD CONSTRAINT portal_password_setup_tokens_pkey PRIMARY KEY (token_hash);

-- CONSTRAINT: quotations quotations_pkey
ALTER TABLE ONLY portal.quotations
    ADD CONSTRAINT quotations_pkey PRIMARY KEY (id);

-- CONSTRAINT: quotations quotations_token_key
ALTER TABLE ONLY portal.quotations
    ADD CONSTRAINT quotations_token_key UNIQUE (token);

-- CONSTRAINT: rectifications rectifications_pkey
ALTER TABLE ONLY portal.rectifications
    ADD CONSTRAINT rectifications_pkey PRIMARY KEY (id);

-- CONSTRAINT: report_versions report_versions_job_version_uq
ALTER TABLE ONLY portal.report_versions
    ADD CONSTRAINT report_versions_job_version_uq UNIQUE (job_id, version);

-- CONSTRAINT: report_versions report_versions_pkey
ALTER TABLE ONLY portal.report_versions
    ADD CONSTRAINT report_versions_pkey PRIMARY KEY (id);

-- CONSTRAINT: review_items review_items_pkey
ALTER TABLE ONLY portal.review_items
    ADD CONSTRAINT review_items_pkey PRIMARY KEY (id);

-- CONSTRAINT: staff_password_reset_tokens staff_password_reset_tokens_pkey
ALTER TABLE ONLY portal.staff_password_reset_tokens
    ADD CONSTRAINT staff_password_reset_tokens_pkey PRIMARY KEY (token_hash);

-- CONSTRAINT: staff_users staff_users_email_unique
ALTER TABLE ONLY portal.staff_users
    ADD CONSTRAINT staff_users_email_unique UNIQUE (email);

-- CONSTRAINT: staff_users staff_users_pkey
ALTER TABLE ONLY portal.staff_users
    ADD CONSTRAINT staff_users_pkey PRIMARY KEY (id);

-- INDEX: applicability_decision_idx
CREATE INDEX applicability_decision_idx ON portal.applicability_determinations USING btree (decision_identity);

-- INDEX: applicability_live_asset_uq
CREATE UNIQUE INDEX applicability_live_asset_uq ON portal.applicability_determinations USING btree (asset_identity, decision_identity) WHERE ((scope = 'asset'::text) AND (superseded_at IS NULL) AND (invalidated_at IS NULL));

-- INDEX: applicability_live_fleet_uq
CREATE UNIQUE INDEX applicability_live_fleet_uq ON portal.applicability_determinations USING btree (fleet_class, decision_identity) WHERE ((scope = 'fleet'::text) AND (superseded_at IS NULL) AND (invalidated_at IS NULL));

-- INDEX: audit_log_job_idx
CREATE INDEX audit_log_job_idx ON portal.audit_log USING btree (job_id);

-- INDEX: audit_log_real_actor_idx
CREATE INDEX audit_log_real_actor_idx ON portal.audit_log USING btree (real_actor_id) WHERE (real_actor_id IS NOT NULL);

-- INDEX: client_users_single_super_user_idx
CREATE UNIQUE INDEX client_users_single_super_user_idx ON portal.client_users USING btree ((true)) WHERE super_user;

-- INDEX: customer_decisions_job_idx
CREATE INDEX customer_decisions_job_idx ON portal.customer_decisions USING btree (job_id);

-- INDEX: customer_decisions_one_live
CREATE UNIQUE INDEX customer_decisions_one_live ON portal.customer_decisions USING btree (issuance_id) WHERE (superseded_at IS NULL);

-- INDEX: engine_snapshots_job_payload_mapping_uq
CREATE UNIQUE INDEX engine_snapshots_job_payload_mapping_uq ON portal.engine_snapshots USING btree (job_id, payload_hash, COALESCE(master_list_version, ''::text));

-- INDEX: governed_rows_section_idx
CREATE INDEX governed_rows_section_idx ON portal.governed_rows USING btree (section);

-- INDEX: governed_rows_zrc_idx
CREATE INDEX governed_rows_zrc_idx ON portal.governed_rows USING btree (zrc);

-- INDEX: issuances_customer_id_idx
CREATE INDEX issuances_customer_id_idx ON portal.issuances USING btree (customer_id);

-- INDEX: issuances_issued_to_email_idx
CREATE INDEX issuances_issued_to_email_idx ON portal.issuances USING btree (issued_to_email);

-- INDEX: issuances_job_id_idx
CREATE INDEX issuances_job_id_idx ON portal.issuances USING btree (job_id);

-- INDEX: job_status_step_revisions_step_idx
CREATE INDEX job_status_step_revisions_step_idx ON portal.job_status_step_revisions USING btree (step_id);

-- INDEX: job_status_steps_job_idx
CREATE INDEX job_status_steps_job_idx ON portal.job_status_steps USING btree (job_id);

-- INDEX: job_status_steps_push_idx
CREATE INDEX job_status_steps_push_idx ON portal.job_status_steps USING btree (push_state);

-- INDEX: job_step_attachments_object_key_uq
CREATE UNIQUE INDEX job_step_attachments_object_key_uq ON portal.job_step_attachments USING btree (object_key) WHERE (object_key IS NOT NULL);

-- INDEX: job_step_attachments_step_idx
CREATE INDEX job_step_attachments_step_idx ON portal.job_step_attachments USING btree (step_id);

-- INDEX: jobs_scheduled_start_idx
CREATE INDEX jobs_scheduled_start_idx ON portal.jobs USING btree (scheduled_start);

-- INDEX: legacy_reports_customer_email_idx
CREATE INDEX legacy_reports_customer_email_idx ON portal.legacy_reports USING btree (customer_email);

-- INDEX: portal_password_reset_email_idx
CREATE INDEX portal_password_reset_email_idx ON portal.portal_password_reset_tokens USING btree (email);

-- INDEX: portal_password_setup_email_idx
CREATE INDEX portal_password_setup_email_idx ON portal.portal_password_setup_tokens USING btree (email);

-- INDEX: quotations_job_idx
CREATE INDEX quotations_job_idx ON portal.quotations USING btree (job_id);

-- INDEX: quotations_one_live
CREATE UNIQUE INDEX quotations_one_live ON portal.quotations USING btree (issuance_id) WHERE (superseded_at IS NULL);

-- INDEX: review_items_job_zrc_active_uq
CREATE UNIQUE INDEX review_items_job_zrc_active_uq ON portal.review_items USING btree (job_id, zrc) WHERE (resolution_state <> 'superseded'::portal.resolution_state);

-- INDEX: staff_password_reset_staff_idx
CREATE INDEX staff_password_reset_staff_idx ON portal.staff_password_reset_tokens USING btree (staff_id);

-- TRIGGER: applicability_determinations applicability_protect
CREATE TRIGGER applicability_protect BEFORE DELETE OR UPDATE ON portal.applicability_determinations FOR EACH ROW EXECUTE FUNCTION portal.gbg_applicability_protect();

-- TRIGGER: applicability_determinations applicability_reviewer_only
CREATE TRIGGER applicability_reviewer_only BEFORE INSERT ON portal.applicability_determinations FOR EACH ROW EXECUTE FUNCTION portal.gbg_applicability_reviewer_only();

-- TRIGGER: audit_log audit_log_append_only
CREATE TRIGGER audit_log_append_only BEFORE DELETE OR UPDATE ON portal.audit_log FOR EACH ROW EXECUTE FUNCTION portal.gbg_audit_log_append_only();

-- TRIGGER: engine_snapshots engine_snapshots_immutable
CREATE TRIGGER engine_snapshots_immutable BEFORE DELETE OR UPDATE ON portal.engine_snapshots FOR EACH ROW EXECUTE FUNCTION portal.gbg_engine_snapshots_immutable();

-- TRIGGER: job_status_step_revisions job_status_step_revisions_append_only
CREATE TRIGGER job_status_step_revisions_append_only BEFORE DELETE OR UPDATE ON portal.job_status_step_revisions FOR EACH ROW EXECUTE FUNCTION portal.gbg_job_status_step_revisions_append_only();

-- TRIGGER: job_status_steps job_status_steps_touch
CREATE TRIGGER job_status_steps_touch BEFORE UPDATE ON portal.job_status_steps FOR EACH ROW EXECUTE FUNCTION portal.gbg_job_status_steps_touch();

-- TRIGGER: job_step_attachments job_step_attachments_token_frozen
CREATE TRIGGER job_step_attachments_token_frozen BEFORE UPDATE ON portal.job_step_attachments FOR EACH ROW EXECUTE FUNCTION portal.gbg_job_step_attachments_token_frozen();

-- TRIGGER: report_versions report_versions_protect
CREATE TRIGGER report_versions_protect BEFORE DELETE OR UPDATE ON portal.report_versions FOR EACH ROW EXECUTE FUNCTION portal.gbg_report_versions_protect();

-- FK CONSTRAINT: applicability_determinations applicability_determinations_confirmed_by_fkey
ALTER TABLE ONLY portal.applicability_determinations
    ADD CONSTRAINT applicability_determinations_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: applicability_determinations applicability_determinations_superseded_by_fkey
ALTER TABLE ONLY portal.applicability_determinations
    ADD CONSTRAINT applicability_determinations_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES portal.applicability_determinations(id);

-- FK CONSTRAINT: audit_log audit_log_job_id_jobs_id_fk
ALTER TABLE ONLY portal.audit_log
    ADD CONSTRAINT audit_log_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: customer_decisions customer_decisions_issuance_id_fkey
ALTER TABLE ONLY portal.customer_decisions
    ADD CONSTRAINT customer_decisions_issuance_id_fkey FOREIGN KEY (issuance_id) REFERENCES portal.issuances(id);

-- FK CONSTRAINT: customer_decisions customer_decisions_job_id_fkey
ALTER TABLE ONLY portal.customer_decisions
    ADD CONSTRAINT customer_decisions_job_id_fkey FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: engine_snapshots engine_snapshots_job_id_jobs_id_fk
ALTER TABLE ONLY portal.engine_snapshots
    ADD CONSTRAINT engine_snapshots_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: issuances issuances_issued_by_staff_users_id_fk
ALTER TABLE ONLY portal.issuances
    ADD CONSTRAINT issuances_issued_by_staff_users_id_fk FOREIGN KEY (issued_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: issuances issuances_job_id_jobs_id_fk
ALTER TABLE ONLY portal.issuances
    ADD CONSTRAINT issuances_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: issuances issuances_report_version_id_report_versions_id_fk
ALTER TABLE ONLY portal.issuances
    ADD CONSTRAINT issuances_report_version_id_report_versions_id_fk FOREIGN KEY (report_version_id) REFERENCES portal.report_versions(id);

-- FK CONSTRAINT: issuances issuances_revoked_by_staff_users_id_fk
ALTER TABLE ONLY portal.issuances
    ADD CONSTRAINT issuances_revoked_by_staff_users_id_fk FOREIGN KEY (revoked_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: job_status_step_revisions job_status_step_revisions_step_id_fkey
ALTER TABLE ONLY portal.job_status_step_revisions
    ADD CONSTRAINT job_status_step_revisions_step_id_fkey FOREIGN KEY (step_id) REFERENCES portal.job_status_steps(id);

-- FK CONSTRAINT: job_status_step_revisions job_status_step_revisions_submitted_by_fkey
ALTER TABLE ONLY portal.job_status_step_revisions
    ADD CONSTRAINT job_status_step_revisions_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: job_status_steps job_status_steps_job_id_fkey
ALTER TABLE ONLY portal.job_status_steps
    ADD CONSTRAINT job_status_steps_job_id_fkey FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: job_status_steps job_status_steps_last_saved_by_fkey
ALTER TABLE ONLY portal.job_status_steps
    ADD CONSTRAINT job_status_steps_last_saved_by_fkey FOREIGN KEY (last_saved_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: job_status_steps job_status_steps_submitted_by_fkey
ALTER TABLE ONLY portal.job_status_steps
    ADD CONSTRAINT job_status_steps_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: job_step_attachments job_step_attachments_step_id_fkey
ALTER TABLE ONLY portal.job_step_attachments
    ADD CONSTRAINT job_step_attachments_step_id_fkey FOREIGN KEY (step_id) REFERENCES portal.job_status_steps(id);

-- FK CONSTRAINT: job_step_attachments job_step_attachments_uploaded_by_fkey
ALTER TABLE ONLY portal.job_step_attachments
    ADD CONSTRAINT job_step_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: jobs jobs_assigned_reviewer_id_staff_users_id_fk
ALTER TABLE ONLY portal.jobs
    ADD CONSTRAINT jobs_assigned_reviewer_id_staff_users_id_fk FOREIGN KEY (assigned_reviewer_id) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: jobs jobs_current_report_version_id_report_versions_id_fk
ALTER TABLE ONLY portal.jobs
    ADD CONSTRAINT jobs_current_report_version_id_report_versions_id_fk FOREIGN KEY (current_report_version_id) REFERENCES portal.report_versions(id);

-- FK CONSTRAINT: jobs jobs_current_snapshot_id_engine_snapshots_id_fk
ALTER TABLE ONLY portal.jobs
    ADD CONSTRAINT jobs_current_snapshot_id_engine_snapshots_id_fk FOREIGN KEY (current_snapshot_id) REFERENCES portal.engine_snapshots(id);

-- FK CONSTRAINT: quotations quotations_created_by_fkey
ALTER TABLE ONLY portal.quotations
    ADD CONSTRAINT quotations_created_by_fkey FOREIGN KEY (created_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: quotations quotations_issuance_id_fkey
ALTER TABLE ONLY portal.quotations
    ADD CONSTRAINT quotations_issuance_id_fkey FOREIGN KEY (issuance_id) REFERENCES portal.issuances(id);

-- FK CONSTRAINT: quotations quotations_job_id_fkey
ALTER TABLE ONLY portal.quotations
    ADD CONSTRAINT quotations_job_id_fkey FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: rectifications rectifications_closed_by_staff_users_id_fk
ALTER TABLE ONLY portal.rectifications
    ADD CONSTRAINT rectifications_closed_by_staff_users_id_fk FOREIGN KEY (closed_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: rectifications rectifications_job_id_jobs_id_fk
ALTER TABLE ONLY portal.rectifications
    ADD CONSTRAINT rectifications_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: rectifications rectifications_raised_by_staff_users_id_fk
ALTER TABLE ONLY portal.rectifications
    ADD CONSTRAINT rectifications_raised_by_staff_users_id_fk FOREIGN KEY (raised_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: rectifications rectifications_reinspection_snapshot_id_engine_snapshots_id_fk
ALTER TABLE ONLY portal.rectifications
    ADD CONSTRAINT rectifications_reinspection_snapshot_id_engine_snapshots_id_fk FOREIGN KEY (reinspection_snapshot_id) REFERENCES portal.engine_snapshots(id);

-- FK CONSTRAINT: rectifications rectifications_review_item_id_review_items_id_fk
ALTER TABLE ONLY portal.rectifications
    ADD CONSTRAINT rectifications_review_item_id_review_items_id_fk FOREIGN KEY (review_item_id) REFERENCES portal.review_items(id);

-- FK CONSTRAINT: report_versions report_versions_job_id_jobs_id_fk
ALTER TABLE ONLY portal.report_versions
    ADD CONSTRAINT report_versions_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: report_versions report_versions_locked_by_staff_users_id_fk
ALTER TABLE ONLY portal.report_versions
    ADD CONSTRAINT report_versions_locked_by_staff_users_id_fk FOREIGN KEY (locked_by) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: report_versions report_versions_snapshot_id_engine_snapshots_id_fk
ALTER TABLE ONLY portal.report_versions
    ADD CONSTRAINT report_versions_snapshot_id_engine_snapshots_id_fk FOREIGN KEY (snapshot_id) REFERENCES portal.engine_snapshots(id);

-- FK CONSTRAINT: review_items review_items_job_id_jobs_id_fk
ALTER TABLE ONLY portal.review_items
    ADD CONSTRAINT review_items_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES portal.jobs(id);

-- FK CONSTRAINT: review_items review_items_reviewer_id_staff_users_id_fk
ALTER TABLE ONLY portal.review_items
    ADD CONSTRAINT review_items_reviewer_id_staff_users_id_fk FOREIGN KEY (reviewer_id) REFERENCES portal.staff_users(id);

-- FK CONSTRAINT: review_items review_items_snapshot_id_engine_snapshots_id_fk
ALTER TABLE ONLY portal.review_items
    ADD CONSTRAINT review_items_snapshot_id_engine_snapshots_id_fk FOREIGN KEY (snapshot_id) REFERENCES portal.engine_snapshots(id);

-- FK CONSTRAINT: review_items review_items_superseded_by_id_review_items_id_fk
ALTER TABLE ONLY portal.review_items
    ADD CONSTRAINT review_items_superseded_by_id_review_items_id_fk FOREIGN KEY (superseded_by_id) REFERENCES portal.review_items(id);

-- FK CONSTRAINT: staff_password_reset_tokens staff_password_reset_tokens_staff_id_fkey
ALTER TABLE ONLY portal.staff_password_reset_tokens
    ADD CONSTRAINT staff_password_reset_tokens_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES portal.staff_users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


-- The Drizzle migration journal, as `drizzle.__drizzle_migrations` holds it in `gbg`.
CREATE TABLE portal.__drizzle_migrations (
    id serial PRIMARY KEY,
    hash text NOT NULL,
    created_at bigint
);

-- References that pointed at the retired mirror now hold jms ids. No foreign keys into
-- jms: its rows are soft-deleted, never removed, and schemas stay migration-independent.
COMMENT ON COLUMN portal.client_users.customer_id IS 'jms.customers.id';
COMMENT ON COLUMN portal.issuances.customer_id IS 'jms.customers.id';
COMMENT ON COLUMN portal.jobs.customer_id IS 'jms.customers.id';
COMMENT ON COLUMN portal.jobs.asset_id IS 'jms.assets.id';
ALTER TABLE portal.jobs ADD COLUMN jms_job_id uuid;
COMMENT ON COLUMN portal.jobs.jms_job_id IS 'jms.jobs.id for zuper_job_uid';
CREATE INDEX jobs_jms_job_idx ON portal.jobs (jms_job_id);
CREATE INDEX jobs_customer_idx ON portal.jobs (customer_id);
CREATE INDEX issuances_customer_idx ON portal.issuances (customer_id);
ALTER TABLE portal.portal_enrollment_pins ADD COLUMN jms_customer_id uuid;
COMMENT ON COLUMN portal.portal_enrollment_pins.jms_customer_id IS 'jms.customers.id for customer_uid';

-- Business OS pattern: every table carries the tenant and has row-level security.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY string_to_array('applicability_determinations,audit_log,client_users,customer_decisions,engine_snapshots,governed_drt_rules,governed_rows,governed_seed_state,issuances,job_status_step_revisions,job_status_steps,job_step_attachments,jobs,legacy_reports,notifications,portal_enrollment_pins,portal_password_reset_tokens,portal_password_setup_tokens,quotations,rectifications,report_versions,review_items,staff_password_reset_tokens,staff_users,__drizzle_migrations', ',') LOOP
    EXECUTE format('ALTER TABLE portal.%I ADD COLUMN tenant_id uuid NOT NULL DEFAULT %L REFERENCES core.tenants(id)', t, '00000000-0000-0000-0000-000000000001');
    EXECUTE format('CREATE INDEX %I ON portal.%I (tenant_id)', t || '_tenant_idx', t);
    EXECUTE format('ALTER TABLE portal.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY service_role_all ON portal.%I FOR ALL TO service_role USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;

COMMIT;

