-- 0005 — the AMC Engine's own data, in schema `amc`.
--
-- Translated by hand from the production SQLite schema (reminders.db, 2026-09-17). Names are
-- kept so the engine's queries change as little as possible. Left out: zuper_jobs,
-- zuper_job_assignees and zuper_webhook_events — `jms.*` and Zupersync replace them.
--
-- Types:
--   INTEGER PRIMARY KEY AUTOINCREMENT → bigint identity (BY DEFAULT, so ids copy unchanged;
--                                       sequences are reset after the copy)
--   0/1 flags                         → boolean
--   SQLite 'YYYY-MM-DD HH:MM:SS' (UTC) and ISO strings → timestamptz
--   date-only strings                 → date
--   display times ('9:00 AM', '14:30') stay text; mixed JSON/plain values stay text
--   JSON that is always valid (audit metadata, child_job_uids) → jsonb
--   epoch milliseconds (booking_holds) → bigint
--
-- References to Zuper records keep their uid columns (the engine still writes to Zuper) and
-- gain a jms uuid column, filled by the copy. No foreign keys into jms (see
-- docs/DATABASE-MERGE.md).
--
-- Secrets (the Zuper token, WhatsApp keys, the booking secret) are NOT stored in these
-- tables; the copy moves them to Supabase Vault, readable through amc.secret().
BEGIN;

CREATE SCHEMA IF NOT EXISTS amc;

-- ── accounts and places ──────────────────────────────────────────────────────

CREATE TABLE amc.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    name text,
    role text DEFAULT 'user',
    created_at timestamptz DEFAULT now()
);

CREATE TABLE amc.locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zuper_property_uid text UNIQUE,
    name text NOT NULL,
    address text,
    is_active boolean DEFAULT true,
    is_default boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE amc.location_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id bigint NOT NULL REFERENCES amc.locations(id) ON DELETE CASCADE,
    key text NOT NULL,
    value text NOT NULL,
    updated_at timestamptz DEFAULT now(),
    UNIQUE (location_id, key)
);
CREATE INDEX idx_location_settings_loc ON amc.location_settings (location_id);

CREATE TABLE amc.user_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES amc.users(id) ON DELETE CASCADE,
    location_id bigint NOT NULL REFERENCES amc.locations(id) ON DELETE CASCADE,
    role text NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'manager', 'viewer')),
    created_at timestamptz DEFAULT now(),
    UNIQUE (user_id, location_id)
);
CREATE INDEX idx_user_locations_user ON amc.user_locations (user_id);
CREATE INDEX idx_user_locations_loc ON amc.user_locations (location_id);

CREATE TABLE amc.password_resets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES amc.users(id),
    token_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    requested_ip text,
    created_at timestamptz DEFAULT now()
);
CREATE INDEX idx_password_resets_token ON amc.password_resets (token_hash);
CREATE INDEX idx_password_resets_user ON amc.password_resets (user_id);

CREATE TABLE amc.settings (
    key text PRIMARY KEY,
    value text NOT NULL,
    updated_at timestamptz DEFAULT now()
);

-- ── reminders ────────────────────────────────────────────────────────────────

CREATE TABLE amc.reminder_campaigns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id bigint NOT NULL DEFAULT 1 REFERENCES amc.locations(id),
    week_start date NOT NULL,
    week_end date NOT NULL,
    status text DEFAULT 'active' CHECK (status IN ('active', 'completed', 'archived')),
    last_synced_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    UNIQUE (week_start, week_end, location_id)
);
CREATE INDEX idx_campaigns_status ON amc.reminder_campaigns (status);
CREATE INDEX idx_campaigns_location ON amc.reminder_campaigns (location_id);

CREATE TABLE amc.reminders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id bigint NOT NULL REFERENCES amc.reminder_campaigns(id),
    job_uid text NOT NULL,
    jms_job_id uuid,
    work_order_number text,
    customer_uid text NOT NULL,
    jms_customer_id uuid,
    customer_name text,
    customer_phone text,
    job_category text,
    job_title text,
    scheduled_date date,
    scheduled_time text,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'scheduled', 'completed', 'no_response', 'failed', 'no_phone')),
    reminder_count integer DEFAULT 0,
    last_reminder_sent_at timestamptz,
    scheduled_at timestamptz,
    scheduled_by text,
    buggy_position integer,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    assigned_mechanic_uid text,
    assigned_mechanic_name text,
    asset_name text,
    asset_serial_number text,
    asset_code text,
    workshop_location text,
    slot_label text,
    child_job_uids jsonb,
    UNIQUE (campaign_id, job_uid)
);
CREATE INDEX idx_reminders_campaign_id ON amc.reminders (campaign_id);
CREATE INDEX idx_reminders_job_uid ON amc.reminders (job_uid);
CREATE INDEX idx_reminders_status ON amc.reminders (status);
CREATE INDEX idx_reminders_scheduled_date ON amc.reminders (scheduled_date);
CREATE INDEX idx_reminders_jms_job ON amc.reminders (jms_job_id);

CREATE TABLE amc.reminder_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reminder_id bigint NOT NULL REFERENCES amc.reminders(id),
    whatsapp_message_id text,
    phone_number text,
    template_name text,
    sent_at timestamptz DEFAULT now(),
    status text DEFAULT 'sent' CHECK (status IN ('sent', 'delivered', 'read', 'failed')),
    error_message text
);
CREATE INDEX idx_reminder_messages_reminder_id ON amc.reminder_messages (reminder_id);
CREATE INDEX idx_reminder_messages_wa_id ON amc.reminder_messages (whatsapp_message_id);

CREATE TABLE amc.scheduled_job_reminders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_uid text NOT NULL,
    jms_job_id uuid,
    work_order_number text,
    customer_uid text,
    customer_name text,
    customer_phone text,
    asset_name text,
    asset_serial_number text,
    scheduled_date date NOT NULL,
    scheduled_time text,
    slot_label text,
    reminder_type text NOT NULL CHECK (reminder_type IN ('day_before', 'same_day')),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    whatsapp_message_id text,
    template_name text,
    sent_at timestamptz,
    error_message text,
    location_id bigint REFERENCES amc.locations(id),
    created_at timestamptz DEFAULT now(),
    UNIQUE (job_uid, reminder_type)
);
CREATE INDEX idx_scheduled_job_reminders_job_uid ON amc.scheduled_job_reminders (job_uid);

CREATE TABLE amc.whatsapp_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id text,
    phone text NOT NULL,
    template_name text NOT NULL,
    message_type text NOT NULL DEFAULT 'other',
    status text DEFAULT 'sent',
    error_message text,
    job_uid text,
    jms_job_id uuid,
    work_order_number text,
    customer_name text,
    location_id bigint,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    idempotency_key text
);
CREATE INDEX idx_wa_messages_status ON amc.whatsapp_messages (status);
CREATE INDEX idx_wa_messages_created ON amc.whatsapp_messages (created_at);
CREATE INDEX idx_wa_messages_msgid ON amc.whatsapp_messages (message_id);
CREATE UNIQUE INDEX idx_wa_messages_idem ON amc.whatsapp_messages (idempotency_key) WHERE idempotency_key IS NOT NULL;

-- ── bookings and technicians ─────────────────────────────────────────────────

CREATE TABLE amc.technician_day_offs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mechanic_uid text NOT NULL,
    jms_user_id uuid,
    mechanic_name text NOT NULL,
    date date NOT NULL,
    period text NOT NULL DEFAULT 'full_day' CHECK (period IN ('full_day', 'morning', 'afternoon')),
    reason text,
    created_by text,
    location_id bigint REFERENCES amc.locations(id),
    created_at timestamptz DEFAULT now(),
    UNIQUE (mechanic_uid, date, period)
);
CREATE INDEX idx_day_offs_date ON amc.technician_day_offs (date);
CREATE INDEX idx_day_offs_mechanic ON amc.technician_day_offs (mechanic_uid);

CREATE TABLE amc.excluded_customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_uid text NOT NULL UNIQUE,
    jms_customer_id uuid,
    customer_name text,
    reason text,
    excluded_by text,
    created_at timestamptz DEFAULT now(),
    location_id bigint
);

CREATE TABLE amc.booking_activity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_uid text NOT NULL,
    jms_job_id uuid,
    work_order_number text,
    customer_uid text,
    customer_name text,
    customer_phone text,
    asset_name text,
    action text NOT NULL CHECK (action IN ('confirmed', 'rescheduled', 'cancelled')),
    booked_by text,
    scheduled_date date,
    scheduled_time text,
    slot_label text,
    mechanic_name text,
    location_id bigint,
    details text,           -- mostly JSON, but not always
    created_at timestamptz DEFAULT now()
);
CREATE INDEX idx_booking_activity_job ON amc.booking_activity (job_uid);
CREATE INDEX idx_booking_activity_date ON amc.booking_activity (created_at);

CREATE TABLE amc.slot_reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    slot_label text NOT NULL,
    position_number integer NOT NULL,
    location_id bigint REFERENCES amc.locations(id),
    job_uid text,
    reserved_at timestamptz DEFAULT now(),
    expires_at timestamptz NOT NULL,
    UNIQUE (date, slot_label, position_number, location_id)
);

CREATE TABLE amc.booking_holds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    slot_label text,
    position_number integer,
    location_id bigint,
    tech_uid text NOT NULL,
    jms_user_id uuid,
    start_ts bigint NOT NULL,   -- epoch milliseconds
    end_ts bigint NOT NULL,
    created_at timestamptz DEFAULT now(),
    expires_at timestamptz NOT NULL
);
CREATE INDEX idx_booking_holds_date ON amc.booking_holds (date, expires_at);

-- ── audit: one table per area, as the engine writes them ─────────────────────

DO $$
DECLARE area text;
BEGIN
  FOREACH area IN ARRAY ARRAY['auth', 'settings', 'users', 'locations', 'bookings', 'reminders', 'dayoffs'] LOOP
    EXECUTE format($f$
      CREATE TABLE amc.%1$I (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          created_at timestamptz NOT NULL DEFAULT now(),
          actor_type text NOT NULL DEFAULT 'user',
          user_id bigint,
          user_email text,
          user_role text,
          location_id bigint,
          action text NOT NULL,
          entity_type text,
          entity_id text,
          summary text,
          metadata jsonb,
          method text,
          path text,
          status_code integer,
          ip text,
          request_id text
      );
      CREATE INDEX %2$I ON amc.%1$I (created_at);
      CREATE INDEX %3$I ON amc.%1$I (user_id);
      CREATE INDEX %4$I ON amc.%1$I (action);
      CREATE INDEX %5$I ON amc.%1$I (entity_type, entity_id);
    $f$, 'audit_' || area, 'idx_audit_' || area || '_created', 'idx_audit_' || area || '_user',
         'idx_audit_' || area || '_action', 'idx_audit_' || area || '_entity');
  END LOOP;
END $$;

CREATE VIEW amc.audit_all AS
  SELECT 'auth' AS domain, * FROM amc.audit_auth
  UNION ALL SELECT 'settings', * FROM amc.audit_settings
  UNION ALL SELECT 'users', * FROM amc.audit_users
  UNION ALL SELECT 'locations', * FROM amc.audit_locations
  UNION ALL SELECT 'bookings', * FROM amc.audit_bookings
  UNION ALL SELECT 'reminders', * FROM amc.audit_reminders
  UNION ALL SELECT 'dayoffs', * FROM amc.audit_dayoffs;

-- ── Business OS pattern: tenant and row-level security on every table ────────

DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'amc' LOOP
    EXECUTE format('ALTER TABLE amc.%I ADD COLUMN tenant_id uuid NOT NULL DEFAULT %L REFERENCES core.tenants(id)', t, '00000000-0000-0000-0000-000000000001');
    EXECUTE format('CREATE INDEX %I ON amc.%I (tenant_id)', t || '_tenant_idx', t);
    EXECUTE format('ALTER TABLE amc.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY service_role_all ON amc.%I FOR ALL TO service_role USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;

-- ── secrets ──────────────────────────────────────────────────────────────────

-- The engine's API keys live in Supabase Vault as 'amc/<key>' (global) and
-- 'amc/location/<location id>/<key>'. This is the only way to read them.
CREATE OR REPLACE FUNCTION amc.secret(p_name text) RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = vault, pg_temp AS $$
    SELECT decrypted_secret FROM vault.decrypted_secrets
     WHERE name = 'amc/' || p_name
     ORDER BY created_at DESC LIMIT 1
$$;
REVOKE ALL ON FUNCTION amc.secret(text) FROM PUBLIC;
COMMENT ON FUNCTION amc.secret(text) IS
  'AMC engine secrets from Vault: amc.secret(''zuper_api_token''), amc.secret(''location/3/whatsapp_api_key'').';

COMMIT;
