"""
Generate migrations/0004_portal_schema.sql from the production `gbg` structure dump.

    ssh tgbgaws 'docker exec g13ju6epg6wnum4nabolt8se sh -c "pg_dump -U \\"$POSTGRES_USER\\" -d gbg \\
        --schema-only --no-owner --no-privileges"' > gbg-schema.sql
    python scripts/merge/gen-portal-schema.py gbg-schema.sql > migrations/0004_portal_schema.sql

Why generated: the portals' tables carry partial unique indexes, CHECK constraints, 16 enum
types and 8 protection triggers. Retyping them invites drift; moving the production
definitions keeps them exact.

What changes on the way:
  * everything moves from `public` to `portal`;
  * the Zuper mirror (customers, assets, zuper_records, zuper_webhook_events,
    zuper_sync_runs) is left out, with every index, sequence and foreign key that belongs
    to it — `jms.*` replaces it;
  * the `gbg_*` trigger functions get `SET search_path = portal, pg_temp`, because their
    bodies name tables unqualified;
  * pg_dump's session preamble (`\\restrict`, SET lines — `transaction_timeout` is
    Postgres 17 only, Supabase runs 15) is dropped.
The Business OS additions (tenant_id, row-level security) and the jms reference columns
are appended by hand at the end of this script, not guessed from the dump.
"""

import re
import sys

RETIRED = {"customers", "assets", "zuper_records", "zuper_webhook_events", "zuper_sync_runs"}
TENANT = "00000000-0000-0000-0000-000000000001"

sys.stdout.reconfigure(encoding="utf-8", newline="\n")   # Windows would write its code page
src = open(sys.argv[1], encoding="utf-8").read().replace("\r\n", "\n")

# Split into (header, body) blocks on pg_dump's object headers.
parts = re.split(r"\n--\n-- (Name: [^\n]+)\n--\n", src)
blocks = [(parts[i], parts[i + 1]) for i in range(1, len(parts), 2)]


def retired(body: str, name: str) -> bool:
    first = name.split(" ")[0]
    for t in RETIRED:
        # A sequence is named after its table (zuper_webhook_events_id_seq), which the
        # word-boundary patterns below do not catch.
        if first == t or first.startswith(t + "_id_seq"):
            return True
        if re.search(rf"\b(?:TABLE(?: ONLY)?|ON|SEQUENCE|OWNED BY) public\.{t}\b", body):
            return True
        if re.search(rf"REFERENCES public\.{t}\(", body):
            return True
    return False


out = []
tables = []
kept = {"TYPE": 0, "FUNCTION": 0, "TABLE": 0, "SEQUENCE": 0, "SEQUENCE OWNED BY": 0, "DEFAULT": 0,
        "CONSTRAINT": 0, "FK CONSTRAINT": 0, "INDEX": 0, "TRIGGER": 0}
for header, body in blocks:
    m = re.match(r"Name: (.+?); Type: (.+?); Schema: (.+?); Owner:", header)
    if not m:
        continue
    name, kind, schema = m.groups()
    if schema != "public":          # the drizzle schema and its journal are recreated below
        continue
    if kind == "COMMENT":
        continue
    body = body.strip()
    body = re.sub(r"^\\(un)?restrict .*$", "", body, flags=re.M).strip()
    if retired(body, name):
        continue
    body = body.replace("public.", "portal.")
    if kind == "FUNCTION":
        body = re.sub(r"\n(\s*)AS \$\$", r"\n\1SET search_path TO portal, pg_temp\n\1AS $$", body, count=1)
    if kind == "TABLE":
        tables.append(re.match(r"CREATE TABLE portal\.(\w+)", body).group(1))
    kept[kind] = kept.get(kind, 0) + 1
    out.append(f"-- {kind}: {name}\n{body}\n")

tables_sql = ",".join(tables + ["__drizzle_migrations"])
print(f"""-- 0004 — the portals' own data, in schema `portal`.
--
-- GENERATED by scripts/merge/gen-portal-schema.py from the production `gbg` structure
-- (pg_dump --schema-only, 2026-09-17). Edit the generator, not this file.
--
-- Kept from `gbg`: {', '.join(f'{v} {k.lower()}' for k, v in kept.items() if v)}.
-- Left out: the Zuper mirror ({', '.join(sorted(RETIRED))}) — `jms.*` replaces it.
-- See docs/DATABASE-MERGE.md.
BEGIN;

CREATE SCHEMA IF NOT EXISTS portal;
""")
print("\n".join(out))

print(f"""
-- The Drizzle migration journal, as `drizzle.__drizzle_migrations` holds it in `gbg`.
CREATE TABLE portal.__drizzle_migrations (
    id serial PRIMARY KEY,
    hash text NOT NULL,
    created_at bigint
);

-- References that pointed at the retired mirror now hold jms ids. No foreign keys into
-- jms: its rows are soft-deleted, never removed, and schemas stay migration-independent.
COMMENT ON COLUMN portal.client_users.customer_id IS 'jms.customers.id';
COMMENT ON COLUMN portal.issuances.customer_id IS 'jms.customers.id';
COMMENT ON COLUMN portal.jobs.customer_id IS 'jms.customers.id';
COMMENT ON COLUMN portal.jobs.asset_id IS 'jms.assets.id';
ALTER TABLE portal.jobs ADD COLUMN jms_job_id uuid;
COMMENT ON COLUMN portal.jobs.jms_job_id IS 'jms.jobs.id for zuper_job_uid';
CREATE INDEX jobs_jms_job_idx ON portal.jobs (jms_job_id);
CREATE INDEX jobs_customer_idx ON portal.jobs (customer_id);
CREATE INDEX issuances_customer_idx ON portal.issuances (customer_id);
ALTER TABLE portal.portal_enrollment_pins ADD COLUMN jms_customer_id uuid;
COMMENT ON COLUMN portal.portal_enrollment_pins.jms_customer_id IS 'jms.customers.id for customer_uid';

-- Business OS pattern: every table carries the tenant and has row-level security.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY string_to_array('{tables_sql}', ',') LOOP
    EXECUTE format('ALTER TABLE portal.%I ADD COLUMN tenant_id uuid NOT NULL DEFAULT %L REFERENCES core.tenants(id)', t, '{TENANT}');
    EXECUTE format('CREATE INDEX %I ON portal.%I (tenant_id)', t || '_tenant_idx', t);
    EXECUTE format('ALTER TABLE portal.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY service_role_all ON portal.%I FOR ALL TO service_role USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;

COMMIT;
""")
